"""
services/agents
================

This module exposes all agent entry-points for the Aegis multi-agent system.

Each agent is implemented as a standalone Python module, and registered
into the agent registry (MCP-style) by the orchestrator at runtime.

This file provides:
- A clean, unified import surface for all agents
- Easy access for the orchestrator, evaluator, and AgentCreator
- Documentation for judges and developers

Agents included:
- MarketResearchAgent
- CopyAgent
- WebDevAgent
- AnalyticsAgent (optional, can be auto-generated by AgentCreator)
- AgentCreator (meta-agent responsible for self-evolution)

All agents follow the same interface:

    def agent_function(args: dict, context: dict) -> dict:
        return { ... }

They are registered at startup using:

    register_agent("AgentName", description, agent_function)

This allows the MCP gateway or the orchestrator to dynamically route tasks
to the appropriate agent.

"""

# Import concrete agent implementations
from .market_research_agent import market_research_agent
from .copy_agent import copy_agent
from .webdev_agent import webdev_agent

# Optional: generated dynamically by AgentCreator
try:
    from .analytics_agent import analytics_agent
except ImportError:
    analytics_agent = None  # Not generated yet

# Meta-agent for creating new agents
from .agent_creator import AgentCreator

__all__ = [
    "market_research_agent",
    "copy_agent",
    "webdev_agent",
    "analytics_agent",
    "AgentCreator",
]
