"""
router.py
---------
The Router is responsible for selecting the correct agent or tool
to execute each step in the orchestration pipeline.

It serves as the "routing brain" which maps:
    - plan steps --> agent names
    - agent names --> actual callables via MCP-style registry
    - fallback routing for non-existent agents
    - A2A (Agent-as-a-Tool) delegation

This component is intentionally lightweight and modular, matching the
MCP-style tool registry used elsewhere in the project.

Author: Harisankar
Project: Aegis - Self-Evolving Agent Fleet
"""

from typing import Dict, Any, Optional


class Router:
    """
    Router resolves which agent/tool should execute the given step.

    Parameters
    ----------
    registry : MCPRegistry-like object
        Must implement:
            - get(agent_name)
            - exists(agent_name)
            - list_agents()

    Notes
    -----
    The planner produces a mission plan like:
        [{"step": "research", "agent": "MarketResearchAgent", "args": {...}}, ...]

    The router ensures the correct target agent is selected
    and provides graceful fallback behavior.
    """

    def __init__(self, registry):
        self.registry = registry

    # ------------------------------------------------------------------
    # 1. Resolve specific agent name from plan
    # ------------------------------------------------------------------
    def resolve_agent(self, agent_name: str) -> Optional[Dict[str, Any]]:
        """
        Resolve the agent/tool specified in a plan step.
        Returns the agent entry if found, else None.
        """
        if self.registry.exists(agent_name):
            return self.registry.get(agent_name)
        return None

    # ------------------------------------------------------------------
    # 2. Automatic fallback routing
    # ------------------------------------------------------------------
    def fallback_agent(self, step_name: str) -> Optional[Dict[str, Any]]:
        """
        If planner references an unknown agent, attempt fallback routing.

        Example:
            - "analytics" step might route to "AnalyticsAgent"
              if automatically generated by AgentCreator.

        Strategy:
            - Try step_name + "Agent"
            - Try lowercase variations
        """
        candidate_names = [
            f"{step_name}Agent",
            f"{step_name.capitalize()}Agent",
            f"{step_name.lower()}_agent",
        ]

        for name in candidate_names:
            if self.registry.exists(name):
                return self.registry.get(name)

        return None

    # ------------------------------------------------------------------
    # 3. Select the best agent for this step (primary API)
    # ------------------------------------------------------------------
    def select(self, step: Dict[str, Any]) -> Dict[str, Any]:
        """
        Given a plan step, choose the appropriate agent/tool.

        Parameters
        ----------
        step : dict
            Dictionary containing:
                - "agent" : name
                - "args"  : arguments

        Returns
        -------
        agent_entry : dict
            Registry entry with:
                - "name"
                - "description"
                - "callable"

        Raises
        ------
        RuntimeError if no suitable agent is found.
        """
        step_name = step.get("step")
        agent_name = step.get("agent")

        # Primary: exact match
        agent_entry = self.resolve_agent(agent_name)
        if agent_entry:
            return agent_entry

        # Fallback: based on step name patterns
        fallback = self.fallback_agent(step_name)
        if fallback:
            return fallback

        # If still not resolved: fatal
        raise RuntimeError(
            f"[Router] No agent found for step '{step_name}' "
            f"(requested agent '{agent_name}')"
        )

    # ------------------------------------------------------------------
    # 4. A2A Delegation (Agent-as-a-Tool)
    # ------------------------------------------------------------------
    def a2a_delegate(self, delegating_agent: str, target_agent: str):
        """
        Allow an agent to call another agent as a 'tool'.

        Example:
            Router.a2a_delegate("CopyAgent", "MarketResearchAgent")
        """
        if not self.registry.exists(delegating_agent):
            raise ValueError(f"Delegating agent '{delegating_agent}' not found.")

        if not self.registry.exists(target_agent):
            raise ValueError(f"Target agent '{target_agent}' not found.")

        delegate_entry = self.registry.get(delegating_agent)
        target_entry = self.registry.get(target_agent)

        # Attach target agent to delegating agent's callable
        # so that agent can invoke: context["delegate"](...)
        if "delegates" not in delegate_entry:
            delegate_entry["delegates"] = {}

        delegate_entry["delegates"][target_agent] = target_entry["callable"]

        return True

    # ------------------------------------------------------------------
    # 5. Introspection Helpers
    # ------------------------------------------------------------------
    def list_available_agents(self):
        """Return all registered agent names."""
        return self.registry.list_agents()

    def debug_print_registry(self):
        """Debug print of all registered agents."""
        print("\n[Router] Registered Agents / Tools:")
        for name in self.registry.list_agents():
            print(" -", name)
